stages:
- test
- deploy

cache:
  paths:
    - game/frontend/node_modules/
    - game/backend/node_modules/
sast:
  stage: test

eslint:
  image: node:lts-alpine3.14
  stage: test
  script:
    - cd game/backend
    - npm install
    - npm run eslint
    - cd ../frontend
    - npm install
    - npm run eslint

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk update
    - apk add git
    - "which ssh-agent || ( apk add openssh-client )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - DEPLOY_SERVER=$DEPLOY_SERVER
    - BRANCH=$CI_COMMIT_BRANCH
    - ssh node-host@${DEPLOY_SERVER} ./startHeadless.sh $BRANCH

include:
- template: Security/SAST.gitlab-ci.yml
